# Generated by Django 4.2.11 on 2024-04-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ingrediente_pedido_pizza_userprofile_delete_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='ingredientes',
            new_name='id_ingredientes',
        ),
    ]
